# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.13
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell

  - repo: local
    hooks:
      - id: tombi-toml-format
        name: tombi format .
        entry: uv run tombi format .
        language: system
        types: [toml]

      - id: tombi-toml-lint
        name: tombi lint .
        entry: uv run tombi lint .
        language: system
        types: [toml]

      - id: ty
        name: ty check
        entry: uv run ty check .
        language: system
        pass_filenames: false
